apiVersion: v1
kind: Service
metadata:
  name: ticket-booking-app-service
spec:
  selector:
    app: ticket-booking-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
